### ISSUE TITLE
sqlite启动时创建数据库失败

### ISSUE THREAD

**Issue by ByboyCn** [NeuCharFramework/NCF#102]
[07] 2022-02-08 11:13:08.0563           added Api path: /api/WeChat_OfficialAccount/MediaApi/UploadForeverVideoAsync
[07] 2022-02-08 11:13:08.0566           Api Task Count:16
[07] 2022-02-08 11:13:08.0623                    create type:   - WeChat_OfficialAccountController
[07] 2022-02-08 11:13:08.0624           ==== Finish BuildWebApi for WeChat_OfficialAccount / Total Time: 679 ms ====
[07] 2022-02-08 11:13:08.0626
[01] 2022-02-08 11:13:08.0653
[01] 2022-02-08 11:13:08.0653                       Category Name |       API Count|       Cost Time |        Average
[01] 2022-02-08 11:13:08.0655           --------------------------------------------------------------------------------
[01] 2022-02-08 11:13:08.0663                  WeChat_MiniProgram |             146|       415.157ms |        2.844ms
[01] 2022-02-08 11:13:08.0664                         WeChat_Open |             164|      414.4167ms |        2.527ms
[01] 2022-02-08 11:13:08.0665                         WeChat_Work |             320|      553.8318ms |        1.731ms
[01] 2022-02-08 11:13:08.0669           Senparc.Xncf.DatabaseToolkit |               1|      105.9367ms |      105.937ms
[01] 2022-02-08 11:13:08.0685              WeChat_OfficialAccount |             776|      681.1814ms |        0.878ms
[01] 2022-02-08 11:13:08.0688           ================================================================================
[01] 2022-02-08 11:13:08.0715                               Total |  API Count:1407| Cost:807.6594ms |
[01] 2022-02-08 11:13:08.0716           Total Average Cost: 0.574 ms            Task Count: 16
[01] 2022-02-08 11:13:08.0719
SenparcEntities 动态加载：Register | DbContextType:SystemServiceEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:DatabaseToolkitEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:XncfBuilderEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:WeixinSenparcEntities_Sqlite
         SenparcEntitiesDbContextBase OnModelCreating：SystemServiceEntities_Sqlite
                 entity type: Senparc.Core.Models.AdminUserInfo
Hosting environment: Development
Content root path: C:\Users\Administrator\Desktop\NCF-Developer\src\Senparc.Web
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
         SenparcEntitiesDbContextBase OnModelCreating：SenparcEntitiesMultiTenant
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.TenantInfo
         NcfUninstallException from TenantMiddleware
SenparcEntities 动态加载：Register | DbContextType:SystemServiceEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:DatabaseToolkitEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:XncfBuilderEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:WeixinSenparcEntities_Sqlite
         SenparcEntitiesDbContextBase OnModelCreating：SystemServiceEntities_Sqlite
                 entity type: Senparc.Core.Models.AdminUserInfo
         NcfUninstallException from TenantMiddleware
进入安装程序，检测是否需要初始化
SenparcEntities 动态加载：Register | DbContextType:SystemServiceEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:DatabaseToolkitEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:XncfBuilderEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:WeixinSenparcEntities_Sqlite
         SenparcEntitiesDbContextBase OnModelCreating：SystemServiceEntities_Sqlite
                 entity type: Senparc.Core.Models.AdminUserInfo
SenparcEntities 动态加载：Register | DbContextType:SystemServiceEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:DatabaseToolkitEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:XncfBuilderEntities_Sqlite
SenparcEntities 动态加载：Register | DbContextType:WeixinSenparcEntities_Sqlite
         SenparcEntitiesDbContextBase OnModelCreating：SystemServiceEntities_Sqlite
                 entity type: Senparc.Core.Models.AdminUserInfo
                 entity type: Senparc.Core.Models.FeedBack
                 entity type: Senparc.Ncf.Core.Models.Account
                 entity type: Senparc.Ncf.Core.Models.AccountPayLog
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.SysButton
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.SysMenu
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.SysPermission
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.SysRole
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.SysRoleAdminUserInfo
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.TenantInfo
                 entity type: Senparc.Ncf.Core.Models.DataBaseModel.XncfModule
                 entity type: Senparc.Ncf.Core.Models.PointsLog
                 entity type: Senparc.Ncf.Core.Models.SystemConfig
                 entity type: Senparc.Xncf.DatabaseToolkit.DbConfig
                 entity type: Senparc.Xncf.WeixinManager.Models.MpAccount
                 entity type: Senparc.Xncf.WeixinManager.Models.UserTag
                 entity type: Senparc.Xncf.WeixinManager.Models.UserTag_WeixinUser
                 entity type: Senparc.Xncf.WeixinManager.Models.WeixinUser
                 entity type: Senparc.Xncf.XncfBuilder.Config
SQLite Error 1: 'no such table: TenantInfos'.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: TenantInfos'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Senparc.Ncf.Repository.RepositoryBase`1.GetFirstOrDefaultObjectAsync(Expression`1 where, String[] includes)
         at Senparc.Ncf.Service.ServiceBase`1.GetObjectAsync(Expression`1 where, String[] includes)
         at Senparc.Ncf.Service.TenantInfoService.CreateOrUpdateTenantInfoAsync(CreateOrUpdate_TenantInfoDto createOrUpdate_TenantInfoDto, Boolean throwIfExisted)
         at Senparc.Ncf.Service.TenantInfoService.CreateInitTenantInfoAsync(HttpContext httpContext)
         at Senparc.Web.Pages.Install.IndexModel.OnGetAsync() in C:\Users\Administrator\Desktop\NCF-Developer\src\Senparc.Web\Pages\Install\Index.cshtml.cs:line 118
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Senparc.Ncf.Service.MultiTenant.TenantMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by JeffreySu** [comment]
1、在Senparc.Web项目的appsettings.json中，确认一下 `EnableMultiTenant` 参数默认应该是 false，如果还出现错误可以换成 true。
2、另外也有收到反馈，最新SQLite官方库的Migrate似乎有点问题，如果您那边有其他数据库，比如MySQL，可以先用MySQL等数据库说一下，确保程序先可以跑起来。

**Comment by ByboyCn** [comment]
没问题了,刚刚数据库名称没填写,抱歉,现在新的问题,按照https://www.cnblogs.com/szw/p/WeChatSampleBuilder-V2.html#Web-WeChatSampleBuilder文章写的,添加nuget版本0.1.0后,程序跑不起来了
![image](https://user-images.githubusercontent.com/17998816/152913077-3a8cf5f0-8a3c-48dc-94b6-1d2c6eb025be.png)
![image](https://user-images.githubusercontent.com/17998816/152913179-160332c9-9d83-4985-b319-6e9da3ca2501.png)
![image](https://user-images.githubusercontent.com/17998816/152913213-ca1e040e-afbb-4c53-9e4f-e19d42a6ff76.png)
添加版本0.3.5.3后,依旧跑不起来
![image](https://user-images.githubusercontent.com/17998816/152913349-aa2c41e6-2590-4b0e-93a4-2b5f8bdc056d.png)

**Comment by JeffreySu** [comment]
把所有的Senparc开头的Nuget包都升级到最新版本，应该是有版本没有匹配（FunctionBase这个类已经没有了）。

正巧我们在发布一个新版本，您可以先用当前的版本试一下，1个小时后就可以看到新发布的版本（只是基础库Nuget包更新，NCF项目不需要更新）

**Comment by JeffreySu** [comment]
已经提前完成新版本发布，直接更新最新的 Nuget 包即可。
