### ISSUE TITLE
参考文档，运行 NCF ;  未能执行成功

### ISSUE THREAD

**Issue by wechatdeveloper** [NeuCharFramework/NCF#81]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Senparc.Ncf.Core.NcfUninstallException: TriedMatching 为 false，推测系统未进行安装
   at Senparc.Ncf.Core.MultiTenant.MultiTenantHelper.TryGetAndCheckRequestTenantInfo(IServiceProvider serviceProvider, String referenceMethod, DbContext dbContext)
   at Senparc.Ncf.Core.Models.SenparcEntitiesDbContextBase.SetGlobalQuery[T](ModelBuilder builder)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Senparc.Ncf.Core.Models.SenparcEntitiesDbContextBase.OnModelCreating(ModelBuilder modelBuilder)
   at Senparc.Ncf.Core.Models.SenparcEntitiesBase.OnModelCreating(ModelBuilder modelBuilder)
   at Senparc.Core.Models.SenparcEntities.OnModelCreating(ModelBuilder modelBuilder) in E:\05_Senparc\NCF\src\Senparc.Core\Models\SenparcEntities.cs:line 58
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()

DB NCF 创建成功， 表没有创建
![image](https://user-images.githubusercontent.com/64650091/129430693-ac44cb68-826a-4611-8fce-2bf703d78658.png)

**Comment by wechatdeveloper** [comment]
#82  Closed
